---
- hosts: all
  become: true
  tasks:
    - name: content
      copy: >
         content='{{inventory_hostname}} {{ansible_default_ipv4.address}}-{{ansible_default_ipv4.macaddress}}\n'
         dest=/var/www/html/ola.html
  #     notify: reload httpd
  #
  # handlers:
  #   - name: reload httpd
  #     service: name=httpd state=reloaded enabled=true
